import * as anchor from "@coral-xyz/anchor";
import { AnchorProvider, BN, Program, type Wallet } from "@coral-xyz/anchor";
import {
  ASSOCIATED_TOKEN_PROGRAM_ID,
  createAssociatedTokenAccountInstruction,
  createInitializeMintInstruction,
  createInitializeTransferHookInstruction,
  createMintToInstruction,
  createTransferCheckedWithTransferHookInstruction,
  ExtensionType,
  getAssociatedTokenAddressSync,
  getMintLen,
  TOKEN_2022_PROGRAM_ID,
} from "@solana/spl-token";
import {
  Connection,
  Keypair,
  PublicKey,
  SystemProgram,
  Transaction,
  type TransactionInstruction,
  type Signer,
  sendAndConfirmTransaction,
} from "@solana/web3.js";

import idl from "./idl/onleash_hook.json";

export const ONLEASH_PROGRAM_ID = new PublicKey(
  "7vJ2fa6dr3Tnx8whNAepUMmpytAnEZxcASMyH2jAuG7v",
);

export const POLICY_SEED = Buffer.from("policy");
export const META_LIST_SEED = Buffer.from("extra-account-metas");

export interface PolicyAccount {
  authority: PublicKey;
  mint: PublicKey;
  perTxMax: BN;
  dailyCap: BN;
  dayStartUnix: BN;
  spentToday: BN;
  destinationAllowlist: PublicKey[];
}

export interface DeployProtectedMintParams {
  /** Decimals for the mint (e.g. 6 for USDC-style). */
  decimals: number;
  /** Per-tx max in raw units (e.g. 10 * 10^decimals). */
  perTxMax: bigint;
  /** Daily cap in raw units. */
  dailyCap: bigint;
  /** Up to 8 destination token-account pubkeys allowed to receive transfers. */
  allowlist: PublicKey[];
  /** Pre-generated mint keypair. If omitted, one is generated. */
  mintKeypair?: Keypair;
}

export interface DeployProtectedMintResult {
  mint: PublicKey;
  policy: PublicKey;
  metaList: PublicKey;
  signatures: {
    createMint: string;
    initMetaList: string;
    initPolicy: string;
  };
}

/**
 * Compute the per-mint Policy PDA address.
 */
export function policyPda(mint: PublicKey): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [POLICY_SEED, mint.toBuffer()],
    ONLEASH_PROGRAM_ID,
  );
}

/**
 * Compute the per-mint ExtraAccountMetaList PDA address (token-2022 contract).
 */
export function metaListPda(mint: PublicKey): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [META_LIST_SEED, mint.toBuffer()],
    ONLEASH_PROGRAM_ID,
  );
}

/**
 * Onleash client — the primary surface of @onleash/sdk.
 *
 * Wraps an Anchor program handle plus token-2022 helpers so you can:
 *   - create a transfer-hook-protected Token-2022 mint
 *   - initialize / update its on-chain Policy
 *   - send transfers that automatically go through the hook
 *   - read policy state
 */
export class OnleashClient {
  readonly program: Program;
  readonly provider: AnchorProvider;
  readonly programId: PublicKey;

  constructor(connection: Connection, wallet: Wallet) {
    this.provider = new AnchorProvider(connection, wallet, {
      commitment: "confirmed",
    });
    // The IDL JSON shipped with the SDK is the source of truth; the OnleashHook
    // type generated by Anchor lives in the program crate and is intentionally
    // not bundled in @onleash/sdk to keep this package framework-agnostic.
    this.program = new Program(idl as anchor.Idl, this.provider);
    this.programId = ONLEASH_PROGRAM_ID;
  }

  get connection(): Connection {
    return this.provider.connection;
  }

  get wallet(): Wallet {
    return this.provider.wallet as Wallet;
  }

  // ─── Reads ─────────────────────────────────────────────────────────────

  policyPda(mint: PublicKey): PublicKey {
    return policyPda(mint)[0];
  }

  metaListPda(mint: PublicKey): PublicKey {
    return metaListPda(mint)[0];
  }

  async fetchPolicy(mint: PublicKey): Promise<PolicyAccount> {
    const pda = this.policyPda(mint);
    // Anchor exposes account types via this.program.account.<name>.
    const raw = await (this.program.account as any).policy.fetch(pda);
    return raw as PolicyAccount;
  }

  async tryFetchPolicy(mint: PublicKey): Promise<PolicyAccount | null> {
    try {
      return await this.fetchPolicy(mint);
    } catch {
      return null;
    }
  }

  // ─── Single-purpose instruction builders ───────────────────────────────

  async ixInitializeExtraAccountMetaList(params: {
    payer: PublicKey;
    mint: PublicKey;
  }): Promise<TransactionInstruction> {
    return await this.program.methods
      .initializeExtraAccountMetaList()
      .accounts({
        payer: params.payer,
        mint: params.mint,
      } as any)
      .instruction();
  }

  async ixInitPolicy(params: {
    authority: PublicKey;
    mint: PublicKey;
    perTxMax: bigint;
    dailyCap: bigint;
    allowlist: PublicKey[];
  }): Promise<TransactionInstruction> {
    return await this.program.methods
      .initPolicy(
        new BN(params.perTxMax.toString()),
        new BN(params.dailyCap.toString()),
        params.allowlist,
      )
      .accounts({
        authority: params.authority,
        mint: params.mint,
      } as any)
      .instruction();
  }

  async ixUpdatePolicy(params: {
    authority: PublicKey;
    mint: PublicKey;
    perTxMax?: bigint | null;
    dailyCap?: bigint | null;
    allowlist?: PublicKey[] | null;
  }): Promise<TransactionInstruction> {
    return await this.program.methods
      .updatePolicy(
        params.perTxMax != null ? new BN(params.perTxMax.toString()) : null,
        params.dailyCap != null ? new BN(params.dailyCap.toString()) : null,
        params.allowlist ?? null,
      )
      .accounts({
        authority: params.authority,
        mint: params.mint,
      } as any)
      .instruction();
  }

  // ─── Composite flows ───────────────────────────────────────────────────

  /**
   * Create a Token-2022 mint with the Onleash transfer hook attached, initialize
   * the ExtraAccountMetaList, and seed an initial Policy. Three signed transactions.
   *
   * The wallet passed to the constructor is the mint authority and policy authority.
   */
  async deployProtectedMint(
    params: DeployProtectedMintParams,
  ): Promise<DeployProtectedMintResult> {
    const wallet = this.wallet;
    const conn = this.connection;
    const mintKp = params.mintKeypair ?? Keypair.generate();
    const mint = mintKp.publicKey;

    // 1. Create mint with TransferHook extension
    const mintLen = getMintLen([ExtensionType.TransferHook]);
    const lamports = await conn.getMinimumBalanceForRentExemption(mintLen);

    const createMintTx = new Transaction().add(
      SystemProgram.createAccount({
        fromPubkey: wallet.publicKey,
        newAccountPubkey: mint,
        space: mintLen,
        lamports,
        programId: TOKEN_2022_PROGRAM_ID,
      }),
      createInitializeTransferHookInstruction(
        mint,
        wallet.publicKey,
        this.programId,
        TOKEN_2022_PROGRAM_ID,
      ),
      createInitializeMintInstruction(
        mint,
        params.decimals,
        wallet.publicKey,
        null,
        TOKEN_2022_PROGRAM_ID,
      ),
    );
    const createMintSig = await sendAndConfirmTransaction(
      conn,
      createMintTx,
      [(wallet as any).payer, mintKp],
    );

    // 2. Initialize ExtraAccountMetaList
    const initMetaIx = await this.ixInitializeExtraAccountMetaList({
      payer: wallet.publicKey,
      mint,
    });
    const initMetaSig = await sendAndConfirmTransaction(
      conn,
      new Transaction().add(initMetaIx),
      [(wallet as any).payer],
      { skipPreflight: true, commitment: "confirmed" },
    );

    // 3. Initialize Policy
    const initPolicyIx = await this.ixInitPolicy({
      authority: wallet.publicKey,
      mint,
      perTxMax: params.perTxMax,
      dailyCap: params.dailyCap,
      allowlist: params.allowlist,
    });
    const initPolicySig = await sendAndConfirmTransaction(
      conn,
      new Transaction().add(initPolicyIx),
      [(wallet as any).payer],
      { commitment: "confirmed" },
    );

    return {
      mint,
      policy: this.policyPda(mint),
      metaList: this.metaListPda(mint),
      signatures: {
        createMint: createMintSig,
        initMetaList: initMetaSig,
        initPolicy: initPolicySig,
      },
    };
  }

  /**
   * Mint tokens to a token account. Standard Token-2022 mintTo, plus account
   * creation if the destination ATA doesn't yet exist. Caller must be mint authority.
   */
  async mintTo(params: {
    mint: PublicKey;
    destinationOwner: PublicKey;
    amount: bigint;
    createAtaIfMissing?: boolean;
  }): Promise<{ destination: PublicKey; signature: string }> {
    const wallet = this.wallet;
    const conn = this.connection;
    const dest = getAssociatedTokenAddressSync(
      params.mint,
      params.destinationOwner,
      false,
      TOKEN_2022_PROGRAM_ID,
      ASSOCIATED_TOKEN_PROGRAM_ID,
    );
    const tx = new Transaction();
    if (params.createAtaIfMissing !== false) {
      const acc = await conn.getAccountInfo(dest);
      if (!acc) {
        tx.add(
          createAssociatedTokenAccountInstruction(
            wallet.publicKey,
            dest,
            params.destinationOwner,
            params.mint,
            TOKEN_2022_PROGRAM_ID,
            ASSOCIATED_TOKEN_PROGRAM_ID,
          ),
        );
      }
    }
    tx.add(
      createMintToInstruction(
        params.mint,
        dest,
        wallet.publicKey,
        params.amount,
        [],
        TOKEN_2022_PROGRAM_ID,
      ),
    );
    const sig = await sendAndConfirmTransaction(conn, tx, [(wallet as any).payer]);
    return { destination: dest, signature: sig };
  }

  /**
   * Send a hooked transfer. Uses createTransferCheckedWithTransferHookInstruction
   * which auto-resolves the ExtraAccountMetaList (so the Policy PDA is included).
   *
   * Returns { signature } on success. Throws on policy violation (the chain reverts
   * the entire transaction atomically — this is the core Onleash guarantee).
   */
  async transfer(params: {
    mint: PublicKey;
    source: PublicKey;
    destination: PublicKey;
    owner: Signer; // current owner of source ATA
    amount: bigint;
    decimals: number;
  }): Promise<{ signature: string }> {
    const ix = await createTransferCheckedWithTransferHookInstruction(
      this.connection,
      params.source,
      params.mint,
      params.destination,
      params.owner.publicKey,
      params.amount,
      params.decimals,
      [],
      "confirmed",
      TOKEN_2022_PROGRAM_ID,
    );
    const tx = new Transaction().add(ix);
    const signature = await sendAndConfirmTransaction(this.connection, tx, [params.owner]);
    return { signature };
  }
  // ─── Spend-log webhook ─────────────────────────────────────────────────

  /**
   * Subscribe to on-chain policy violations for a mint (or all Onleash mints)
   * and POST a structured payload to `webhookUrl` on every rejection.
   *
   * Works by subscribing to Solana logs via `connection.onLogs`. The hook
   * program emits Anchor error codes in the transaction logs on every revert.
   *
   * @param opts.webhookUrl  Developer-configured URL to POST violations to.
   * @param opts.mint        If set, only violations for this mint are reported.
   *                         If omitted, all violations across every Onleash mint
   *                         are reported (useful for a monitoring dashboard).
   * @param opts.onViolation Optional in-process callback, called alongside the POST.
   * @returns An unsubscribe function — call it to stop listening.
   *
   * @example
   * const unsub = client.watchViolations({
   *   mint: myMint,
   *   webhookUrl: "https://your-server.com/onleash-webhook",
   *   onViolation: (v) => console.log("blocked:", v.errorName),
   * });
   * // later: unsub();
   */
  watchViolations(opts: {
    webhookUrl: string;
    mint?: PublicKey;
    onViolation?: (violation: ViolationEvent) => void;
  }): () => void {
    // Subscribe to the policy PDA for a specific mint, or the program itself
    // for all mints. The policy PDA appears in every hooked transfer's account list.
    const listenAddress = opts.mint
      ? this.policyPda(opts.mint)
      : this.programId;

    const subId = this.connection.onLogs(
      listenAddress,
      (logInfo, ctx) => {
        if (!logInfo.err) return; // only care about failures

        const parsed = parseViolation(logInfo.logs, logInfo.signature, ctx.slot);
        if (!parsed) return; // not an Onleash policy revert

        opts.onViolation?.(parsed);

        // Fire-and-forget POST — don't await so we don't block the log callback
        fetch(opts.webhookUrl, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(parsed),
        }).catch((err) => {
          console.error("[onleash] webhook POST failed:", err);
        });
      },
      "confirmed",
    );

    return () => {
      this.connection.removeOnLogsListener(subId);
    };
  }
}

// ─── Violation payload ───────────────────────────────────────────────────────

export interface ViolationEvent {
  /** Transaction signature of the reverted transfer. */
  signature: string;
  /** Numeric Anchor error code (6001–6009). */
  errorCode: number;
  /** Human-readable error name. */
  errorName: string;
  /** Error message from the program. */
  errorMessage: string;
  /** Solana slot the log was observed in. */
  slot: number;
  /** ISO 8601 timestamp of when the event was observed off-chain. */
  observedAt: string;
}

const ONLEASH_ERRORS: Record<number, { name: string; message: string }> = {
  6000: { name: "NotTransferring",       message: "Hook called outside a transfer context" },
  6001: { name: "DestinationNotAllowed", message: "Destination not in allowlist" },
  6002: { name: "ExceedsPerTxMax",       message: "Amount exceeds per-tx maximum" },
  6003: { name: "ExceedsDailyCap",       message: "Amount exceeds daily cap" },
  6004: { name: "AllowlistTooLong",      message: "Allowlist exceeds 8 entries" },
  6005: { name: "Unauthorized",          message: "Non-authority called update_policy" },
  6006: { name: "Overflow",             message: "Math overflow in spent_today" },
  6007: { name: "PolicyPaused",          message: "Policy is paused — all transfers halted" },
  6008: { name: "CooldownActive",        message: "Cooldown active — minimum interval not elapsed" },
  6009: { name: "ExceedsTransferCount",  message: "Daily transfer count limit reached" },
};

// Anchor encodes custom errors as 0x1770 + offset (anchor base = 0x1770 = 6000)
const ANCHOR_BASE = 6000;

function parseViolation(
  logs: string[],
  signature: string,
  slot: number,
): ViolationEvent | null {
  for (const line of logs) {
    // Match "custom program error: 0x177X" (hex) or "Error Number: 6001" (decimal)
    const hexMatch = line.match(/custom program error: 0x([0-9a-fA-F]+)/);
    if (hexMatch) {
      const code = parseInt(hexMatch[1], 16);
      if (code >= ANCHOR_BASE && code < ANCHOR_BASE + 100) {
        const meta = ONLEASH_ERRORS[code];
        if (!meta) return null;
        return { signature, errorCode: code, errorName: meta.name, errorMessage: meta.message, slot, observedAt: new Date().toISOString() };
      }
    }
    const decMatch = line.match(/Error Number: (\d+)/);
    if (decMatch) {
      const code = parseInt(decMatch[1], 10);
      const meta = ONLEASH_ERRORS[code];
      if (meta) {
        return { signature, errorCode: code, errorName: meta.name, errorMessage: meta.message, slot, observedAt: new Date().toISOString() };
      }
    }
  }
  return null;
}
