import * as anchor from "@coral-xyz/anchor";
import { AnchorProvider, BN, Program, type Wallet } from "@coral-xyz/anchor";
import {
  ASSOCIATED_TOKEN_PROGRAM_ID,
  createAssociatedTokenAccountInstruction,
  createInitializeMintInstruction,
  createInitializeTransferHookInstruction,
  createMintToInstruction,
  createTransferCheckedWithTransferHookInstruction,
  ExtensionType,
  getAssociatedTokenAddressSync,
  getMintLen,
  TOKEN_2022_PROGRAM_ID,
} from "@solana/spl-token";
import {
  Connection,
  Keypair,
  PublicKey,
  SystemProgram,
  Transaction,
  type TransactionInstruction,
  type Signer,
  sendAndConfirmTransaction,
} from "@solana/web3.js";

import idl from "./idl/onleash_hook.json";

export const ONLEASH_PROGRAM_ID = new PublicKey(
  "7vJ2fa6dr3Tnx8whNAepUMmpytAnEZxcASMyH2jAuG7v",
);

export const POLICY_SEED = Buffer.from("policy");
export const META_LIST_SEED = Buffer.from("extra-account-metas");

export interface PolicyAccount {
  authority: PublicKey;
  mint: PublicKey;
  perTxMax: BN;
  dailyCap: BN;
  dayStartUnix: BN;
  spentToday: BN;
  destinationAllowlist: PublicKey[];
}

export interface DeployProtectedMintParams {
  /** Decimals for the mint (e.g. 6 for USDC-style). */
  decimals: number;
  /** Per-tx max in raw units (e.g. 10 * 10^decimals). */
  perTxMax: bigint;
  /** Daily cap in raw units. */
  dailyCap: bigint;
  /** Up to 8 destination token-account pubkeys allowed to receive transfers. */
  allowlist: PublicKey[];
  /** Pre-generated mint keypair. If omitted, one is generated. */
  mintKeypair?: Keypair;
}

export interface DeployProtectedMintResult {
  mint: PublicKey;
  policy: PublicKey;
  metaList: PublicKey;
  signatures: {
    createMint: string;
    initMetaList: string;
    initPolicy: string;
  };
}

/**
 * Compute the per-mint Policy PDA address.
 */
export function policyPda(mint: PublicKey): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [POLICY_SEED, mint.toBuffer()],
    ONLEASH_PROGRAM_ID,
  );
}

/**
 * Compute the per-mint ExtraAccountMetaList PDA address (token-2022 contract).
 */
export function metaListPda(mint: PublicKey): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [META_LIST_SEED, mint.toBuffer()],
    ONLEASH_PROGRAM_ID,
  );
}

/**
 * Onleash client — the primary surface of @onleash/sdk.
 *
 * Wraps an Anchor program handle plus token-2022 helpers so you can:
 *   - create a transfer-hook-protected Token-2022 mint
 *   - initialize / update its on-chain Policy
 *   - send transfers that automatically go through the hook
 *   - read policy state
 */
export class OnleashClient {
  readonly program: Program;
  readonly provider: AnchorProvider;
  readonly programId: PublicKey;

  constructor(connection: Connection, wallet: Wallet) {
    this.provider = new AnchorProvider(connection, wallet, {
      commitment: "confirmed",
    });
    // The IDL JSON shipped with the SDK is the source of truth; the OnleashHook
    // type generated by Anchor lives in the program crate and is intentionally
    // not bundled in @onleash/sdk to keep this package framework-agnostic.
    this.program = new Program(idl as anchor.Idl, this.provider);
    this.programId = ONLEASH_PROGRAM_ID;
  }

  get connection(): Connection {
    return this.provider.connection;
  }

  get wallet(): Wallet {
    return this.provider.wallet as Wallet;
  }

  // ─── Reads ─────────────────────────────────────────────────────────────

  policyPda(mint: PublicKey): PublicKey {
    return policyPda(mint)[0];
  }

  metaListPda(mint: PublicKey): PublicKey {
    return metaListPda(mint)[0];
  }

  async fetchPolicy(mint: PublicKey): Promise<PolicyAccount> {
    const pda = this.policyPda(mint);
    // Anchor exposes account types via this.program.account.<name>.
    const raw = await (this.program.account as any).policy.fetch(pda);
    return raw as PolicyAccount;
  }

  async tryFetchPolicy(mint: PublicKey): Promise<PolicyAccount | null> {
    try {
      return await this.fetchPolicy(mint);
    } catch {
      return null;
    }
  }

  // ─── Single-purpose instruction builders ───────────────────────────────

  async ixInitializeExtraAccountMetaList(params: {
    payer: PublicKey;
    mint: PublicKey;
  }): Promise<TransactionInstruction> {
    return await this.program.methods
      .initializeExtraAccountMetaList()
      .accounts({
        payer: params.payer,
        mint: params.mint,
      } as any)
      .instruction();
  }

  async ixInitPolicy(params: {
    authority: PublicKey;
    mint: PublicKey;
    perTxMax: bigint;
    dailyCap: bigint;
    allowlist: PublicKey[];
  }): Promise<TransactionInstruction> {
    return await this.program.methods
      .initPolicy(
        new BN(params.perTxMax.toString()),
        new BN(params.dailyCap.toString()),
        params.allowlist,
      )
      .accounts({
        authority: params.authority,
        mint: params.mint,
      } as any)
      .instruction();
  }

  async ixUpdatePolicy(params: {
    authority: PublicKey;
    mint: PublicKey;
    perTxMax?: bigint | null;
    dailyCap?: bigint | null;
    allowlist?: PublicKey[] | null;
  }): Promise<TransactionInstruction> {
    return await this.program.methods
      .updatePolicy(
        params.perTxMax != null ? new BN(params.perTxMax.toString()) : null,
        params.dailyCap != null ? new BN(params.dailyCap.toString()) : null,
        params.allowlist ?? null,
      )
      .accounts({
        authority: params.authority,
        mint: params.mint,
      } as any)
      .instruction();
  }

  // ─── Composite flows ───────────────────────────────────────────────────

  /**
   * Create a Token-2022 mint with the Onleash transfer hook attached, initialize
   * the ExtraAccountMetaList, and seed an initial Policy. Three signed transactions.
   *
   * The wallet passed to the constructor is the mint authority and policy authority.
   */
  async deployProtectedMint(
    params: DeployProtectedMintParams,
  ): Promise<DeployProtectedMintResult> {
    const wallet = this.wallet;
    const conn = this.connection;
    const mintKp = params.mintKeypair ?? Keypair.generate();
    const mint = mintKp.publicKey;

    // 1. Create mint with TransferHook extension
    const mintLen = getMintLen([ExtensionType.TransferHook]);
    const lamports = await conn.getMinimumBalanceForRentExemption(mintLen);

    const createMintTx = new Transaction().add(
      SystemProgram.createAccount({
        fromPubkey: wallet.publicKey,
        newAccountPubkey: mint,
        space: mintLen,
        lamports,
        programId: TOKEN_2022_PROGRAM_ID,
      }),
      createInitializeTransferHookInstruction(
        mint,
        wallet.publicKey,
        this.programId,
        TOKEN_2022_PROGRAM_ID,
      ),
      createInitializeMintInstruction(
        mint,
        params.decimals,
        wallet.publicKey,
        null,
        TOKEN_2022_PROGRAM_ID,
      ),
    );
    const createMintSig = await sendAndConfirmTransaction(
      conn,
      createMintTx,
      [(wallet as any).payer, mintKp],
    );

    // 2. Initialize ExtraAccountMetaList
    const initMetaIx = await this.ixInitializeExtraAccountMetaList({
      payer: wallet.publicKey,
      mint,
    });
    const initMetaSig = await sendAndConfirmTransaction(
      conn,
      new Transaction().add(initMetaIx),
      [(wallet as any).payer],
      { skipPreflight: true, commitment: "confirmed" },
    );

    // 3. Initialize Policy
    const initPolicyIx = await this.ixInitPolicy({
      authority: wallet.publicKey,
      mint,
      perTxMax: params.perTxMax,
      dailyCap: params.dailyCap,
      allowlist: params.allowlist,
    });
    const initPolicySig = await sendAndConfirmTransaction(
      conn,
      new Transaction().add(initPolicyIx),
      [(wallet as any).payer],
      { commitment: "confirmed" },
    );

    return {
      mint,
      policy: this.policyPda(mint),
      metaList: this.metaListPda(mint),
      signatures: {
        createMint: createMintSig,
        initMetaList: initMetaSig,
        initPolicy: initPolicySig,
      },
    };
  }

  /**
   * Mint tokens to a token account. Standard Token-2022 mintTo, plus account
   * creation if the destination ATA doesn't yet exist. Caller must be mint authority.
   */
  async mintTo(params: {
    mint: PublicKey;
    destinationOwner: PublicKey;
    amount: bigint;
    createAtaIfMissing?: boolean;
  }): Promise<{ destination: PublicKey; signature: string }> {
    const wallet = this.wallet;
    const conn = this.connection;
    const dest = getAssociatedTokenAddressSync(
      params.mint,
      params.destinationOwner,
      false,
      TOKEN_2022_PROGRAM_ID,
      ASSOCIATED_TOKEN_PROGRAM_ID,
    );
    const tx = new Transaction();
    if (params.createAtaIfMissing !== false) {
      const acc = await conn.getAccountInfo(dest);
      if (!acc) {
        tx.add(
          createAssociatedTokenAccountInstruction(
            wallet.publicKey,
            dest,
            params.destinationOwner,
            params.mint,
            TOKEN_2022_PROGRAM_ID,
            ASSOCIATED_TOKEN_PROGRAM_ID,
          ),
        );
      }
    }
    tx.add(
      createMintToInstruction(
        params.mint,
        dest,
        wallet.publicKey,
        params.amount,
        [],
        TOKEN_2022_PROGRAM_ID,
      ),
    );
    const sig = await sendAndConfirmTransaction(conn, tx, [(wallet as any).payer]);
    return { destination: dest, signature: sig };
  }

  /**
   * Send a hooked transfer. Uses createTransferCheckedWithTransferHookInstruction
   * which auto-resolves the ExtraAccountMetaList (so the Policy PDA is included).
   *
   * Returns { signature } on success. Throws on policy violation (the chain reverts
   * the entire transaction atomically — this is the core Onleash guarantee).
   */
  async transfer(params: {
    mint: PublicKey;
    source: PublicKey;
    destination: PublicKey;
    owner: Signer; // current owner of source ATA
    amount: bigint;
    decimals: number;
  }): Promise<{ signature: string }> {
    const ix = await createTransferCheckedWithTransferHookInstruction(
      this.connection,
      params.source,
      params.mint,
      params.destination,
      params.owner.publicKey,
      params.amount,
      params.decimals,
      [],
      "confirmed",
      TOKEN_2022_PROGRAM_ID,
    );
    const tx = new Transaction().add(ix);
    const signature = await sendAndConfirmTransaction(this.connection, tx, [params.owner]);
    return { signature };
  }
}
